name: update push
run-name: ${{ github.actor }} 

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: "./src/package-lock.json"

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_SECRET }}

      - name: Install dependencies
        working-directory: ./src
        run: npm install

      - name: Publish app
        working-directory: ./src
        run: expo publish --non-interactive
